name: Build BLAST container push to quay.io

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: rosalindfranklininstitute+github_blast
          password: ${{ secrets.QUAYIO_TOKEN }}

      - name: Set BLAST version
        run: |
          echo BLAST_VERSION=$([ "$GITHUB_REF_TYPE" = "tag" ] && echo $GITHUB_REF_NAME || curl https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/VERSION 2>/dev/null) >> $GITHUB_ENV

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            quay.io/rosalindfranklininstitute/blast
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          labels: |
            blast-version=${{ env.BLAST_VERSION }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            BLAST_VERSION=${{ env.BLAST_VERSION }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
